### ISSUE TITLE
Instructor Feedback - Problem Statement, Solution, Project Plan

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [mad-java-ent-f20/Trivial#2]
Hi Team! 

Nice job with your problem statement!  This will be a fun project to build and should be a fun demo.

I think some of this is already on your radar, but I'm documenting it here so that you have a way to communicate these items are ready for review.

- [ ] Remember that the main goal of the team project is to build an API that anyone could consume.  Think about the web services that you practiced with in week 8: [swapi](https://swapi.dev), [petstore api](https://petstore.swagger.io), and [zip code api](https://www.zipcodeapi.com). The core "business" here is to provide restful resources and operations.
- [ ] You will likely also have a website that serves as the userguide for the API (refer to the examples above) and the website may also allow a user to test out your API.
- [ ] In your readme.md, be sure to document the resources and methods that you will provide on those resources. Refer to my example in slack #team-project for one example. This will help me understand the scope of your api.
- [ ] Add a project plan - you might check out [this project]( https://github.com/mad-java-ent-f20/MoodyBooze) for some inspiration for this work.

Please let me know when the resources/methods and plan are ready for review by responding to this issue. If you have any questions, please ask!
